const deeds = [
    {   
        type:1,
        status:1,
        authorId:'sadasdssadsad',
        authorName:'moshe ben sa',
        authorImg:'',
        acceptedOffer:'asdasdasdasdasdas',
        acceptedRequest:'',
        createdAt: new Date(),
        neededDay: 'tomorrow',
        neededHour: 18,
        title: 'Walk my dog',
        description: 'She needs attention and love <3',
        adress: 'Ben Gurion 4, Tel Aviv',
        urgency: 'low',
        radius:'700meters'
    },
    {   
        type:1,
        status:1,
        authorId:'sadasdssadsad',
        authorName:'david',
        authorImg:'',
        acceptedOffer:'asdssssssss',
        acceptedRequest:'',
        createdAt: new Date(),
        neededDay: 'tomorrow',
        neededHour: 18,
        title: 'i neew groceries',
        description: 'milk and sugar',
        adress: 'Ben Gurion 4',
        urgency: 'low',
        radius:'700meters'
    },
    {   
        type:2,
        status:1,
        authorId:'sadasdssadsad',
        authorName:'david',
        authorImg:'',
        acceptedOffer:'',
        acceptedRequest:'',
        createdAt: new Date(),
        neededDay: 'tomorrow',
        neededHour: 18,
        title: 'Going to the mall',
        description: 'Someone need something?',
        adress: 'Hahagana tel aviv',
        urgency: 'low',
        radius:'700meters'
    },
    {   
        type:2,
        status:1,
        authorId:'sadasdssadsad',
        authorName:'Rotem',
        authorImg:'',
        acceptedOffer:'asdasdasdasdasdas',
        acceptedRequest:'',
        createdAt: new Date(),
        neededDay: 'tomorrow',
        neededHour: 18,
        title: 'Going to the drugstore',
        description: 'Someone need somthing?',
        adress: 'Ben Gurion 4, Tel Aviv',
        urgency: 'low',
        radius:'700meters'
    },
   
]

export default deeds;